name: Twitter automatic quote post
on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour on the hour
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set execute permissions on chromedriver
        run: chmod +x chromedriver.exe
        
      - name: Check for CSV and chromedriver
        run: |
          ls -l new_quotes.csv   # List the CSV file to ensure it exists
          ls -l chromedriver.exe  # List chromedriver to ensure it exists
    

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies

      - name: Run Python script
        run: python trytwitter.py  # Run your Python script
      - name: Commit and push if CSV file changed
        env:
          GIT_AUTH: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GIT_AUTH}@github.com/ApiramRajamohan/Automate_Twitter.git
          git add new_quotes.csv
          git commit -m "Update CSV file: Removed a row" || echo "No changes to commit"
          git push
